

Que.5 - 

Implement a Decision Tree, Random Forest model to classify the animals in the zoo in to different categories.
Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.

Dataset : Zoo.csv

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings(action="ignore")

In [3]:
df = pd.read_csv("Zoo.csv")
df.head()

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
0,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   hair      101 non-null    int64
 1   feathers  101 non-null    int64
 2   eggs      101 non-null    int64
 3   milk      101 non-null    int64
 4   airborne  101 non-null    int64
 5   aquatic   101 non-null    int64
 6   predator  101 non-null    int64
 7   toothed   101 non-null    int64
 8   backbone  101 non-null    int64
 9   breathes  101 non-null    int64
 10  venomous  101 non-null    int64
 11  fins      101 non-null    int64
 12  legs      101 non-null    int64
 13  tail      101 non-null    int64
 14  domestic  101 non-null    int64
 15  catsize   101 non-null    int64
 16  type      101 non-null    int64
dtypes: int64(17)
memory usage: 13.5 KB

In [5]:
df.corr()

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
hair,1.000000,-0.427851,-0.817382,0.878503,-0.198431,-0.473554,-0.154769,0.492531,0.191681,0.441149,-0.104245,-0.280313,0.394009,0.048973,0.207208,0.455020,-0.562384
feathers,-0.427851,1.000000,0.419248,-0.410761,0.656553,-0.058552,-0.104430,-0.613631,0.231403,0.254588,-0.145739,-0.223541,-0.206686,0.292569,0.031586,-0.135934,-0.197520
eggs,-0.817382,0.419248,1.000000,-0.938848,0.376646,0.376244,0.011605,-0.642150,-0.340420,-0.382777,0.098689,0.164796,-0.224918,-0.221090,-0.155610,-0.514650,0.661825
milk,0.878503,-0.410761,-0.938848,1.000000,-0.366765,-0.362613,-0.029721,0.628168,0.384958,0.423527,-0.242449,-0.156328,0.214196,0.210026,0.163928,0.574906,-0.723683
airborne,-0.198431,0.656553,0.376646,-0.366765,1.000000,-0.172638,-0.295181,-0.594311,-0.104718,0.286039,0.008528,-0.251157,0.043712,0.009482,0.063274,-0.349768,0.022677
aquatic,-0.473554,-0.058552,0.376244,-0.362613,-0.172638,1.000000,0.375978,0.053150,0.022463,-0.637506,0.087915,0.604492,-0.360638,-0.034642,-0.224308,-0.111866,0.326639
predator,-0.154769,-0.104430,0.011605,-0.029721,-0.295181,0.375978,1.000000,0.129452,0.051022,-0.262931,0.115391,0.190302,-0.099723,0.018947,-0.309794,0.144790,0.061179
toothed,0.492531,-0.613631,-0.642150,0.628168,-0.594311,0.053150,0.129452,1.000000,0.575085,-0.065690,-0.062344,0.364292,-0.193476,0.310368,0.069430,0.344010,-0.471527
backbone,0.191681,0.231403,-0.340420,0.384958,-0.104718,0.022463,0.051022,0.575085,1.000000,0.207666,-0.246611,0.209499,-0.432856,0.731762,0.101733,0.356976,-0.828845
breathes,0.441149,0.254588,-0.382777,0.423527,0.286039,-0.637506,-0.262931,-0.065690,0.207666,1.000000,-0.120752,-0.617219,0.369868,0.088952,0.124068,0.204125,-0.519308
venomous,-0.104245,-0.145739,0.098689,-0.242449,0.008528,0.087915,0.115391,-0.062344,-0.246611,-0.120752,1.000000,-0.033956,0.022964,-0.162724,-0.003252,-0.183748,0.321476
fins,-0.280313,-0.223541,0.164796,-0.156328,-0.251157,0.604492,0.190302,0.364292,0.209499,-0.617219,-0.033956,1.000000,-0.605652,0.204349,-0.093887,0.031705,0.099430
legs,0.394009,-0.206686,-0.224918,0.214196,0.043712,-0.360638,-0.099723,-0.193476,-0.432856,0.369868,0.022964,-0.605652,1.000000,-0.348295,0.073931,0.068791,0.131693
tail,0.048973,0.292569,-0.221090,0.210026,0.009482,-0.034642,0.018947,0.310368,0.731762,0.088952,-0.162724,0.204349,-0.348295,1.000000,0.023434,0.243277,-0.631830
domestic,0.207208,0.031586,-0.155610,0.163928,0.063274,-0.224308,-0.309794,0.069430,0.101733,0.124068,-0.003252,-0.093887,0.073931,0.023434,1.000000,0.020073,-0.181043
catsize,0.455020,-0.135934,-0.514650,0.574906,-0.349768,-0.111866,0.144790,0.344010,0.356976,0.204125,-0.183748,0.031705,0.068791,0.243277,0.020073,1.000000,-0.521030
type,-0.562384,-0.197520,0.661825,-0.723683,0.022677,0.326639,0.061179,-0.471527,-0.828845,-0.519308,0.321476,0.099430,0.131693,-0.631830,-0.181043,-0.521030,1.000000

In [6]:
df.drop(['feathers', 'airborne','predator', 'fins', 'legs', 'domestic'], axis=1, inplace=True)

In [7]:
df['type'].value_counts()

type
1    41
2    20
4    13
7    10
6     8
3     5
5     4
Name: count, dtype: int64

In [9]:
x = df.drop('type', axis=1)
y = df['type']

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, train_size=0.7, random_state=123456)

Decision Tree, Random Forest

In [12]:
from sklearn.tree import DecisionTreeClassifier

def create_model_decision_tree_classifier():
    model = DecisionTreeClassifier()
    model.fit(x_train,y_train)
    return model

In [13]:
from sklearn.ensemble import RandomForestClassifier

def create_model_random_forest():
    model = RandomForestClassifier(n_estimators=100)
    model.fit(x_train, y_train)
    return model

In [ ]:
Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def evaluate_model(model):
    # training accuracry
    y_pred = model.predict(x_train)
    y_true = y_train

    # calculate training accuracy
    training_accuracy = accuracy_score(y_true, y_pred)

    # testing accuracy
    y_pred = model.predict(x_test)
    y_true = y_test

    # get the performance metrics for testing
    
    testing_accuracy = accuracy_score(y_true, y_pred)
    testing_precision = precision_score(y_true, y_pred, average='macro')
    testing_recall = recall_score(y_true, y_pred,average='macro')
    testing_f1 = f1_score(y_true, y_pred,average='macro')

    return training_accuracy, testing_accuracy, testing_precision, testing_recall, testing_f1

In [15]:
models = [
    ("Decision Tree", create_model_decision_tree_classifier(), (2, 0)),
    ("Random Forest", create_model_random_forest(), (2, 1)),
]
models

[('Decision Tree', DecisionTreeClassifier(), (2, 0)),
 ('Random Forest', RandomForestClassifier(), (2, 1))]

In [16]:
performance_data = []
for model_name, model, position in models:
    training_accuracy, test_accuracy, precision, recall, f1 = evaluate_model(model)
    performance_data.append([
        model_name,
        f"{training_accuracy * 100:0.2f}%", f"{test_accuracy * 100:0.2f}%",
        precision, 
        recall,        
        f1
    ])
    
performance_chart = pd.DataFrame(performance_data, 
            columns=["Model", "Train Accuracy", "Test Accuracy", "Precision", "Recall", "F1"])
performance_chart

           Model Train Accuracy Test Accuracy  Precision    Recall        F1
0  Decision Tree         98.57%        90.32%   0.833333  0.869048  0.789116
1  Random Forest         98.57%        93.55%   0.904762  0.904762  0.857143